# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "Nano" do
pod 'Venmo-iOS-SDK', '~>1.3'
end

target "NanoTests" do

end

target "NanoTodayExtension" do
pod 'Venmo-iOS-SDK', '~>1.3'
end

