# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "Nano" do
pod 'Venmo-iOS-SDK', '~>1.3'
pod 'SPGooglePlacesAutocomplete'
pod 'iCarousel'
pod 'AFNetworking', '~> 2.4'
end

target "NanoTests" do

end

target "NanoTodayExtension" do
pod 'Venmo-iOS-SDK', '~>1.3'
pod 'AFNetworking', '~> 2.4'
end

